---
- hosts: djangoseller.com
  tasks:
  - name: Restart gunicorn
    supervisorctl: name=gunicorn state=restarted config=/etc/supervisor/conf.d/gunicorn.conf
  - name: Apply django project migrations
    command: python manage.py migrate chdir=/home/root/www/website
  - name: Apply django project collect static
    command: python manage.py collectstatic --noinput chdir=/home/root/www/website
