Vagrant.configure(2) do |config|
  config.vm.box = "giovannicode/djangoseller"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.synced_folder "./source_code/", "/home/vagrant/www/website"
end
