---
- hosts: all
  user: vagrant
  sudo: yes
  tasks: 
    - name: Update Ubuntu Server 
      apt: update_cache=true
  #  - name: Upgrade Ubuntu Server
  #    apt: upgrade=yes
    - name: Install libpq-dev
      apt: pkg=libpq-dev state=installed
    - name: Install python-setuptools
      apt: pkg=python-setuptools state=installed
    - name: Install python-dev
      apt: pkg=python-dev state=installed
    - name: Install pip
      apt: pkg=python-pip state=installed 
    - name: Create requirements directory ifNotExists
      file: path=requirements state=directory
    - name: Copy the local pip requirements file
      copy: src=../requirements/requirements.txt dest=requirements/requirements.txt
    - name: Install python package requirements
      command: sudo pip install -r requirements/requirements.txt
    - name: Installs nginx web server
      apt: pkg=nginx state=installed 
    - name: install postgresql
      apt: pkg=postgresql state=installed
    - name: Install postgresql-contrib 
      apt: pkg=postgresql-contrib 
    - name: Install supervisor
      apt: pkg=supervisor state=installed
    - name: Congfigure postgresql
      script: postgres/config_postgres.sh
    - name: Configure nginx 
      copy: src=nginx/djangoseller dest=/etc/nginx/sites-available/djangoseller
    - name: Create symlinks
      file: src=/etc/nginx/sites-available/djangoseller dest=/etc/nginx/sites-enabled/djangoseller state=link
    - name: Delete default nginx config file.
      file: path=/etc/nginx/sites-enabled/default state=absent
    - name: Create www directory
      file: path=/home/vagrant/www state=directory owner=vagrant group=vagrant recurse=yes
    - name: Create gunicorn directories
      file: path=/home/vagrant/www/gunicorn state=directory
    - name: Configure gunicorn 
      copy: src=gunicorn/conf.py dest=/home/vagrant/www/gunicorn/conf.py
    - name: Create supervisor directories
      file: path=/etc/supervisor/conf.d state=directory
    - name: Create supervisor gunicorn log directories
      file: path=/var/log/supervisor/gunicorn state=directory
    - name: Configure supervisor
      copy: src=supervisor/gunicorn.conf dest=/etc/supervisor/conf.d/gunicorn.conf
    - name: Create Django static directory
      file: path=/home/vagrant/www/static state=directory owner=vagrant group=vagrant recurse=yes
    - name: Create Django media directory
      file: path=/home/vagrant/www/media/ state=directory owner=vagrant group=vagrant recurse=yes
    - name: Create working tree directory
      file: path=/home/vagrant/www/website state=directory
    - name: Restart nginx
      service: name=nginx state=restarted 
    - name: Restart supervisor
      command: service supervisor restart
    - name: Restart gunicorn
      supervisorctl: name=gunicorn state=restarted config=/etc/supervisor/conf.d/gunicorn.conf
    - name: Copy the local env_vars file
      copy: src=environment/env_vars.txt dest=/home/vagrant/env_vars.txt
#    - name: Setup environment variables
#      script: shell_script.sh 
#    - name: Setup Django project
#      sudo: no
#      shell: . /home/vagrant/.bashrc && python /home/vagrant/www/website/manage.py migrate
#    - name: Setup Django project
#      sudo: no
#      shell: . /home/vagrant/.bashrc && python /home/vagrant/www/website/manage.py collectstatic --noinput
#    - name: Run migrations
#      shell: source /home/vagrant/.bashrc && python manage.py migrate 
#      args:
#        chdir: /home/vagrant/www/website
#        executable: /bin/bash
#    - name: Collect static files
#      shell: source /home/vagrant/.bashrc && python manage.py collectstatic --noinput
#      args:
#        chdir: /home/vagrant/www/website
#        executable: /bin/bash
